### ISSUE TITLE
Second sync with owncloud fails

### ISSUE THREAD

**Issue by anyc** [nemomobile/buteo-sync-plugin-carddav#11]
Hi,

with version 0.0.8 the initial sync with owncloud seems to work, thank you! However, afterwards it seems to fail.
In the log, I see one vcard and afterwards the following messages:
```
Feb 18 18:32:23 Jolla carddav-client[639]: [D] CardDav::downsyncComplete:779 - void CardDav::downsyncComplete() downsync complete with total AMR: 2 , 0 , 0 
Feb 18 18:32:23 Jolla carddav-client[639]: [D] Syncer::continueSync:141 - void Syncer::continueSync(const QList<QtContacts::QContact>&, const QList<QtContacts::QContact>&, const QList<QtContacts::QContact>&) storing remote changes to local device: AMR: 2 0 0 for account: 29 
Feb 18 18:32:23 Jolla carddav-client[639]: [W] enforceDetailConstraints:2545 - "Invalid detail type:  0" 
Feb 18 18:32:23 Jolla carddav-client[639]: [W] ContactWriter::save:2414 - "Error updating contact sql-549: 3" 
Feb 18 18:32:23 Jolla carddav-client[639]: [W] enforceDetailConstraints:2545 - "Invalid detail type:  0" 
Feb 18 18:32:23 Jolla carddav-client[639]: [W] ContactWriter::save:2414 - "Error updating contact sql-45: 3" 
Feb 18 18:32:23 Jolla carddav-client[639]: [W] ContactWriter::syncUpdate:4868 - "Unable to save contact changes for sync update" 
Feb 18 18:32:23 Jolla carddav-client[639]: [W] QtContactsSqliteExtensions::TwoWayContactSyncAdapter::storeRemoteChanges:920 - virtual bool QtContactsSqliteExtensions::TwoWayContactSyncAdapter::storeRemoteChanges(const QList<QtContacts::QContact>&, QList<QtContacts::QContact>*, const QString&, bool, const QSet<QtContacts::QContactDetail::DetailType>&) error - couldn't store sync contacts! 
Feb 18 18:32:23 Jolla carddav-client[639]: [W] Syncer::continueSync:143 - void Syncer::continueSync(const QList<QtContacts::QContact>&, const QList<QtContacts::QContact>&, const QList<QtContacts::QContact>&) unable to store remote changes for account 29 
Feb 18 18:32:23 Jolla carddav-client[639]: [D] Buteo::LogTimer::LogTimer:72 - "void CardDavClient::syncFinished(int, const QString&)" :Entry 
Feb 18 18:32:23 Jolla carddav-client[639]: [D] Buteo::LogTimer::~LogTimer:83 - "void CardDavClient::syncFinished(int, const QString&)" :Exit, execution time: 0 ms 
Feb 18 18:32:23 Jolla carddav-client[639]: [C] CardDavClient::syncFinished:137 - CardDAV sync failed: 401 ""
```

**Comment by freerunner** [comment]
Same problem here.

Are there any news on this one?

**Comment by chriadam** [comment]
Which version of the plugin are you using? `devel-su -p pkcon get-details buteo-sync-plugin-carddav`
This issue should have been fixed with the most recent update.

**Comment by anyc** [comment]
Problem still exists here with 0.0.9-1.4.1.armv7hl. By now, I'm using two owncloud servers (private and work) but it's the same problem as before when I was just using one.

**Comment by anyc** [comment]
I think I also recreated both accounts after the last update as, before, I had a separate account for carddav and caldav. But I'm not sure if I deleted all contacts in between or if they were removed automatically after I removed the old accounts.

**Comment by chriadam** [comment]
Can you provide logs?  Requires developer mode:

$ systemctl --user stop msyncd
$ killall msyncd
$ MSYNCD_LOGGING_LEVEL=8 devel-su -p msyncd

then in separate terminal:

$ devel-su journalctl -af | grep carddav

then trigger sync via UI: Settings | Accounts -> longpress CardDAV account -> Sync

Wait until it has finished syncing, and then send the log from the journalctl terminal to me (chris dot adams at jolla dot com).

Thanks!

**Comment by anyc** [comment]
Okay, done.
